name: Homelab Terraform Destroy
run-name: Terraform Homelab Destroying Infra 💥
on:
  workflow_dispatch: # Enables manual triggering from the GitHub Actions UI
jobs:
  tf-destroy:
    runs-on: self-hosted
    environment: homelab-dev
    steps:
    # Debug Info for Step
      - run: >
            echo "Debug Info - Triggered by: ${{ github.event_name }}; Job Running on OS ${{ runner.os }}; Branch ${{ github.ref }}."
      - name: Check Code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}/homelab_infra
          cd ${{ github.workspace }}/homelab_infra
      - run: echo "The env var for TF_STATE_BUCKET ${{ vars.TF_STATE_BUCKET }}."

    # Terraform Destroy the plan
      - name: Terraform Destroy
        uses: dflook/terraform-apply@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SHADA_HOMELAB_DEPLOY_USER_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SHADA_HOMELAB_DEPLOY_USER_SECRET_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            path: ${{ github.workspace }}/homelab_infra
            backend_config: |
                bucket=${{ vars.TF_STATE_BUCKET }}
                key=${{ vars.TF_STATE_BUCKET_KEY }}
                region=${{ vars.TF_STATE_BUCKET_REGION }}
            variables: |
                proxmox_password = "${{ secrets.HOMELAB_PROXMOX_PASSWORD }}"
            auto_approve: true
            destroy: true
        


